apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-go-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-go-api
  template:
    metadata:
      labels:
        app: simple-go-api
    spec:
      containers:
      - name: simple-go-api
        image: tonisanta/simple-go-api
        ports:
        - containerPort: 80
